
#jiangan 测试
##
server:
  port: 4040


eureka:
  client:
    service-url:
      #声明注册地址
      defaultZone: http://localhost:8761/eureka
    #开启注册功能
    register-with-eureka: true


spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://182.254.164.41:3306/zslm?userUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  druid:
    initialSize: 10
    minIdle: 5
    maxActive: 20
    maxWait: 10
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#继续mybatis相关配置
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapUnderscoreToCamelCase: true

