
server:
  port: 4040


order:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.


eureka:
  client:
    service-url:
      #声明注册地址
      defaultZone: http://localhost:8761/eureka
    #开启注册功能
    register-with-eureka: true


spring:
  application:
    name: user


feign:
  hystrix:
    enabled: true

