server:
  port: 5050

eureka:
  client:
    service-url:
      #声明注册地址
      defaultZone: http://localhost:8761/eureka
    #开启注册功能
    register-with-eureka: true


spring:
  application:
    name: prodcut
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.254.164.41:3306/zslm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

feign:
  hystrix:
    enabled: true
pagehelper:
  reasonable: true #分页参数合理化
  support-methods-arguments: true
  params: count=countsql