spring:
  application:
    name: eureka  #服务端名称

server:
  port: 8761  #服务端端口号
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true  #拉取注册表
